"""
Quell CLI — built with Typer.

Commands:
  quell scan        Scan production code for untested guard clauses (PRIMARY)
  quell check       Scan specs, find gaps, optionally fix
  quell reproduce   Bug description → failing test
  quell prove       Confidence score for a function/file
  quell score       Project-wide Quell Score + --badge
  quell ci          CI mode: check + threshold + exit code
  quell init        Add [tool.quell] to pyproject.toml
  quell pr          Analyze requirement coverage for a GitHub PR
  quell install     Set up Quell in your project (pre-commit + GitHub Action)
  quell auth        Manage authentication (login/logout/status)
  quell graph       QuellGraph build/inspect commands
  quell teardown    Stop all quelltest-managed ephemeral containers
"""
from __future__ import annotations

import asyncio
import json as _json
import threading
from collections.abc import Coroutine
from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax
from rich.table import Table

from quell import __version__
from quell.core.models import QuellConfig

app = typer.Typer(
    name="quell",
    help="Your docstrings say what your code should do. Quell proves it.",
    rich_markup_mode="rich",
)
auth_app = typer.Typer(help="Manage Quell authentication")
graph_app = typer.Typer(help="QuellGraph build and inspection commands")
sync_app = typer.Typer(help="Manage cloud sync (Pro/Team) — push, status, history, unlink")
app.add_typer(auth_app, name="auth")
app.add_typer(graph_app, name="graph")
app.add_typer(sync_app, name="sync")

console = Console()

# GitHub Actions workflow template — written by `quell install --action`
GITHUB_ACTION_YAML = """\
name: Quell — Edge Case Scanner

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"

permissions:
  contents: read
  pull-requests: write

jobs:
  quell:
    name: Quell edge case scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Quell
        run: uv pip install quelltest --system

      - name: Run quell find
        id: quell
        run: |
          quell find . --format github 2>&1 | tee quell-output.txt
          echo "prs=$(python -c \\"import json,sys; d=json.load(open('quell-report.json')); print(d.get('summary',{}).get('prs_score',0))\\" 2>/dev/null || echo 0)" >> $GITHUB_OUTPUT

      - name: Post PRS comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let report = {};
            try { report = JSON.parse(fs.readFileSync('quell-report.json', 'utf8')); } catch {}
            const summary = report.summary || {};
            const prs = summary.prs_score ?? 0;
            const written = summary.verified_and_written ?? 0;
            const total = summary.gaps_found ?? 0;
            const tier = prs >= 80 ? '🟢' : prs >= 60 ? '🟡' : '🔴';
            const body = [
              '<!-- quell-bot -->',
              `## ${tier} Quell Production Readiness Score: ${prs}/100`,
              '',
              `| Metric | Value |`,
              `|--------|-------|`,
              `| WRITTEN tests | ${written} |`,
              `| Total edge cases | ${total} |`,
              `| PRS | ${prs}/100 |`,
              '',
              '_Generated by [Quell](https://quell.buildsbyshashank.tech) — edge case finder_',
            ].join('\\n');
            const marker = '<!-- quell-bot -->';
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const existing = comments.find(c => c.body && c.body.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner, repo: context.repo.repo,
                comment_id: existing.id, body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: context.issue.number, body,
              });
            }
"""


def _version_callback(value: bool) -> None:
    if value:
        typer.echo(f"quelltest {__version__}")
        raise typer.Exit()


@app.callback()
def _main(
    version: bool = typer.Option(
        None, "--version", "-V",
        callback=_version_callback,
        is_eager=True,
        help="Show version and exit.",
    ),
) -> None:
    pass


def _load_config(project_root: Path) -> QuellConfig:
    """Load config — returns safe defaults (no LLM) if no config found."""
    try:
        import tomllib
        pyproject = project_root / "pyproject.toml"
        if pyproject.exists():
            data = tomllib.loads(pyproject.read_text())
            quell_cfg = data.get("tool", {}).get("quell", {})
            if quell_cfg:
                return QuellConfig(**quell_cfg)
    except Exception:
        pass
    # Safe defaults — works without any config or API key
    return QuellConfig(
        llm_provider="none",
        enable_docstring=True,
        enable_types=True,
        enable_mutations=False,
        enable_pyspark=False,
    )


def _method_tag(source_value: str, generated_by: str = "") -> str:
    """Return a dim tag showing how this requirement was processed."""
    if source_value == "pyspark":
        return "[dim][pyspark, rule-based, no network][/dim]"
    if generated_by.startswith("llm"):
        return "[dim][llm][/dim]"
    return "[dim][rule-based, no network][/dim]"


def _run_coro(coro: Coroutine[Any, Any, Any]) -> Any:
    """Run a coroutine in a fresh thread with its own event loop.

    Wraps a single async call so the rest of cmd_scan stays synchronous.
    Each call gets an isolated thread — immune to any outer event loop.
    """
    result: list[Any] = [None]
    exc: list[BaseException] = []

    def _target() -> None:
        try:
            result[0] = asyncio.run(coro)
        except BaseException as e:  # noqa: BLE001
            exc.append(e)

    t = threading.Thread(target=_target, daemon=True)
    t.start()
    t.join()
    if exc:
        raise exc[0]
    return result[0]


@app.command("find")
def cmd_find(
    target: Path = typer.Argument(Path("."), help="File or directory to scan for untested edge cases"),
    fix: bool = typer.Option(False, "--fix", help="Write tests for confident cases (WRITTEN bucket)"),
    auto: bool = typer.Option(False, "--auto", help="Skip confirmation prompts (for CI)"),
    use_llm: bool = typer.Option(False, "--use-llm", help="Enable LLM fallback (requires quell auth)"),
    sync: bool = typer.Option(False, "--sync", help="Push report to cloud after scan (Pro/Team only)"),
    project_root: Path = typer.Option(Path("."), "--root"),
    fmt: str = typer.Option("console", "--format", "-f", help="Output format: console or github"),
) -> None:
    """
    Find untested edge cases in your Python code.

    Auto-detects all spec sources: docstrings, Pydantic models, PySpark schemas,
    guard clauses. No flags needed. Rule-based — no LLM, no network, no code
    leaves your machine.

    quell find src/                  find all untested edge cases
    quell find src/ --fix            also write tests for confident cases
    quell find src/ --fix --auto     skip prompts (use in CI)
    quell find src/ --fix --use-llm  enable LLM for harder cases (needs auth)
    quell find src/ --fix --sync     scan, write tests, push report to cloud
    """
    import sys as _sys
    _sys.stderr.write(
        "[quell] Running quell find (primary command from v2.0.0)\n"
    )
    # `find` is a superset of `scan` — delegate to the scan implementation
    # while tagging the source as the unified find command.
    cmd_scan(
        target=target,
        fix=fix,
        suggest=False,
        llm=use_llm,
        no_llm=False,
        project_root=project_root,
        fmt=fmt,
    )

    if sync:
        _do_sync(project_root)


@app.command("scan")
def cmd_scan(
    target: Path = typer.Argument(Path("."), help="File or directory to scan"),
    fix: bool = typer.Option(False, "--fix", help="Generate failing tests for each gap"),
    suggest: bool = typer.Option(False, "--suggest", help="Also suggest code fixes via LLM (requires --llm)"),
    llm: bool = typer.Option(False, "--llm", help="Enable LLM for guard types the rule engine can't handle"),
    no_llm: bool = typer.Option(False, "--no-llm", help="[deprecated] Rule-based only, no LLM (now the default)"),
    project_root: Path = typer.Option(Path("."), "--root"),
    fmt: str = typer.Option("console", "--format", "-f", help="Output format: console or github"),
) -> None:
    """
    [deprecated] Use `quell find` instead. Will be removed in v2.2.

    quell scan src/                   find all logic gaps
    quell scan src/ --fix             generate failing tests (rule-based, no network)
    quell scan src/ --fix --llm       also use LLM for complex guard types
    """
    import sys as _sys
    _sys.stderr.write(
        "[quell] DEPRECATED: `quell scan` has been renamed to `quell find`. "
        "It will be removed in v2.2. Run `quell find` instead.\n"
    )
    # Fully synchronous — no asyncio.run() at the top level.
    # LLM calls inside use _run_coro() which isolates each await in its own thread.
    from quell.core.models import VerificationStatus
    from quell.coverage.checker import CoverageChecker
    from quell.spec.code_guard_reader import CodeGuardReader
    from quell.synthesis.app_locator import find_app
    from quell.synthesis.framework_detector import detect_route
    from quell.synthesis.framework_engine import FrameworkEngine
    from quell.synthesis.rule_engine import RuleEngine

    config = _load_config(project_root)
    app_info = find_app(project_root)
    framework_engine = FrameworkEngine()

    files = (
        [
            f for f in target.rglob("*.py")
            if "test" not in f.name
            and ".venv" not in str(f)
            and "__pycache__" not in str(f)
            and "site-packages" not in str(f)
        ]
        if target.is_dir() else [target]
    )

    if fmt != "github":
        if app_info is not None:
            app_line = (
                f"\n[dim]Framework: {app_info.framework} app "
                f"`{app_info.attr_name}` in {app_info.module_path}[/dim]"
            )
        else:
            app_line = ""
        console.print(Panel.fit(
            f"[bold blue]Quell Scan[/bold blue] — "
            f"reading guard clauses in {len(files)} file(s)\n"
            "[dim]No docstrings needed. Reading your if/raise patterns.[/dim]"
            f"{app_line}"
        ))

    reader = CodeGuardReader()
    checker = CoverageChecker(project_root)
    rule_engine = RuleEngine()

    all_requirements = []
    for f in files:
        all_requirements.extend(reader.read(f))

    if not all_requirements:
        if fmt == "github":
            print("::notice::Quell: No guard clauses found in scanned files.")
        else:
            console.print("[yellow]No guard clauses found.[/yellow]")
            console.print(
                "[dim]Quell reads if/raise patterns. "
                "If your code has no guard clauses, nothing to check.[/dim]"
            )
        return

    all_requirements = checker.check(all_requirements)
    gaps = [r for r in all_requirements if not r.is_covered]

    if fmt == "github":
        # Emit GitHub Actions workflow commands for inline PR annotations
        for req in gaps:
            line_part = f",line={req.source_line}" if req.source_line else ""
            guard_text = (req.raw_spec_text or req.description)
            guard_text = guard_text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
            title = f"Untested guard [{req.constraint_kind.value}] in {req.target_function}()"
            print(f"::warning file={req.target_file}{line_part},title={title}::{guard_text}")
        if not gaps:
            print(f"::notice::Quell: All {len(all_requirements)} guard clauses are tested.")
    else:
        table = Table(
            title=f"Logic Gaps Found ({len(gaps)} untested / {len(all_requirements)} total)"
        )
        table.add_column("File", style="blue")
        table.add_column("Function", style="cyan")
        table.add_column("Guard Clause", style="white")
        table.add_column("Type", style="magenta")
        table.add_column("Method", style="dim")

        for req in gaps:
            table.add_row(
                req.target_file.name,
                req.target_function,
                (req.raw_spec_text or req.description)[:50],
                req.constraint_kind.value,
                "[dim][rule-based, no network][/dim]",
            )

        console.print(table)

    if not gaps:
        if fmt != "github":
            console.print("[green]All guard clauses are tested.[/green]")
        return

    if not fix:
        if fmt != "github":
            console.print(
                f"\n[yellow]Run [bold]quell scan {target} --fix[/bold] "
                "to generate failing tests.[/yellow]"
            )
        # Still write detection-only report
        detection_items = [
            {
                "function": r.target_function,
                "file": str(r.target_file),
                "guard": r.raw_spec_text or r.description,
                "type": r.constraint_kind.value,
                "line": r.source_line,
                "outcome": "detected_not_fixed",
                "reason": "",
                "generated_test": None,
            }
            for r in gaps
        ]
        _write_scan_report(project_root, str(target), all_requirements, gaps, detection_items, 0, fmt)
        return

    # Generate tests + optional fix suggestions
    from quell.core.verifier import Verifier
    from quell.core.writer import Writer

    # LLM is opt-in for scan: user must pass --llm explicitly.
    # --no-llm is kept for backwards compat but is now a no-op (it's already the default).
    use_llm = llm and not no_llm
    llm_client = None
    synthesizer = None
    if use_llm:
        from quell.llm.client import LLMClient
        from quell.synthesis.llm_engine import LLMSynthesizer
        llm_client = LLMClient.from_config(config)
        synthesizer = LLMSynthesizer(llm_client, config)

    if suggest and not use_llm:
        console.print(
            "[yellow]--suggest requires LLM. Pass --llm to enable.[/yellow]"
        )

    verifier = Verifier(config, project_root=project_root)
    writer = Writer(config)
    fixed = 0
    scaffolded_files: set[str] = set()  # deduplicated stub file paths

    # Report tracking — written to quell-report.json at the end
    report_items: list[dict[str, Any]] = []

    for i, req in enumerate(gaps, 1):
        console.print(
            f"\n[{i}/{len(gaps)}] [cyan]{req.target_function}()[/cyan]"
            f" — {req.description[:60]}"
        )
        console.print(f"  Guard: [dim]{req.raw_spec_text}[/dim]")

        item: dict[str, Any] = {
            "function": req.target_function,
            "file": str(req.target_file),
            "guard": req.raw_spec_text or req.description,
            "type": req.constraint_kind.value,
            "outcome": "skipped_no_rule",
            "reason": "",
            "generated_test": None,
        }

        # Route framework handlers through the framework engine first —
        # rule-engine stubs can't drive Depends() / TestClient.
        route = detect_route(req.target_function, req.target_file)
        if route is not None:
            item["type"] = f"{req.constraint_kind.value} (framework:{route.framework})"
            if framework_engine.can_handle(route, app_info):
                assert app_info is not None  # can_handle returns False when app_info is None
                candidate = framework_engine.generate(req, route, app_info)
                generated_by_tag = "[dim][framework, TestClient][/dim]"
                if candidate is None:
                    item["outcome"] = "skipped_framework_unsupported"
                    item["reason"] = f"{route.framework} route — engine couldn't synthesize"
                    console.print(f"  [dim]Skipped — {item['reason']}[/dim]")
                    report_items.append(item)
                    continue
            else:
                item["outcome"] = "skipped_framework_no_app"
                item["reason"] = (
                    f"{route.framework} route detected but no app object "
                    "(FastAPI/Flask instance) found in project — can't build TestClient"
                )
                console.print(f"  [dim]Skipped — {item['reason']}[/dim]")
                report_items.append(item)
                continue
        elif rule_engine.can_handle(req):
            candidate = rule_engine.generate(req)
            generated_by_tag = "[dim][rule-based, no network][/dim]"
            if candidate is None:
                # Async is now handled via asyncio.run wrap; only structural
                # reasons cause a None return: self.attr or local variable.
                if "self." in (req.raw_spec_text or ""):
                    item["outcome"] = "skipped_local_var"
                    item["reason"] = "guard checks self.attr — needs class instantiation"
                else:
                    item["outcome"] = "skipped_local_var"
                    item["reason"] = (
                        "guard variable is a local variable (DB result, computed value) "
                        "not a function parameter — can't inject via stub"
                    )
                _write_scaffold(req, None, 2, config, project_root, item, scaffolded_files, console, fmt)
                report_items.append(item)
                continue
        elif synthesizer:
            # LLM call — run in isolated thread to avoid event loop conflicts
            candidate = _run_coro(synthesizer.synthesize(req))
            generated_by_tag = "[dim][llm][/dim]"
        else:
            item["reason"] = f"no rule for {req.constraint_kind.value} — pass --llm"
            console.print(
                f"  [dim]Skipped ({req.constraint_kind.value}) — "
                "no rule for this guard type. Pass --llm to use LLM.[/dim]"
            )
            _write_scaffold(req, None, 1, config, project_root, item, scaffolded_files, console, fmt)
            report_items.append(item)
            continue

        if not candidate:
            item["outcome"] = "skipped_no_gen"
            item["reason"] = "synthesizer returned no test"
            _write_scaffold(req, None, 2, config, project_root, item, scaffolded_files, console, fmt)
            report_items.append(item)
            continue

        item["generated_test"] = candidate.test_code

        with console.status("Verifying test fails on current code (proving gap)..."):
            result = verifier.verify(req, candidate)

        if result.status == VerificationStatus.VERIFIED:
            item["outcome"] = "verified"
            console.print(
                f"  [green]Gap proven[/green] — test fails on current code "
                f"{generated_by_tag}"
            )
            console.print(Syntax(candidate.test_code, "python", theme="monokai"))

            if suggest and use_llm and llm_client is not None:
                from quell.fix.suggester import FixSuggester
                suggester_obj = FixSuggester(llm_client, config)
                with console.status("Generating fix suggestion..."):
                    fix_suggestion = _run_coro(suggester_obj.suggest(req, candidate))

                if fix_suggestion and fix_suggestion.verified:
                    console.print(
                        "\n  [bold green]Fix suggestion "
                        "(verified to make test pass):[/bold green]"
                    )
                    console.print(f"  {fix_suggestion.explanation}")
                    console.print(Syntax(fix_suggestion.diff, "diff", theme="monokai"))
                    apply = typer.confirm("  Apply this fix?", default=False)
                    if apply:
                        req.target_file.write_text(
                            req.target_file.read_text(encoding="utf-8").replace(
                                fix_suggestion.original_code,
                                fix_suggestion.suggested_code,
                                1,
                            ),
                            encoding="utf-8",
                        )
                        console.print("  [green]Fix applied[/green]")
                elif fix_suggestion:
                    console.print(
                        "  [yellow]Fix suggested but not verified — review manually[/yellow]"
                    )
                    console.print(Syntax(fix_suggestion.diff, "diff", theme="monokai"))

            write = typer.confirm("  Write this test?", default=True)
            if write:
                if writer.write(candidate, req.id):
                    console.print(
                        f"  [green]Test written → {candidate.test_file_path}[/green]"
                    )
                    fixed += 1

        elif result.status == VerificationStatus.DOESNT_CATCH_VIOLATION:
            item["outcome"] = "rejected_no_catch"
            item["reason"] = "test passes even when the guard is violated"
            console.print(
                "  [yellow]Test generated but doesn't catch the gap — needs manual review[/yellow]"
            )
        elif result.status == VerificationStatus.FAILS_ON_CORRECT:
            item["outcome"] = "rejected_fails_on_correct"
            # Surface the first meaningful line of the pytest output so the
            # diagnostic report shows the REAL failure (ImportError, missing
            # env var, app startup error, etc.) instead of a generic blurb.
            err_snippet = _summarize_pytest_failure(result.error_message or "")
            item["reason"] = err_snippet or (
                "generated stub args trigger a different error on valid code — "
                "function likely has complex/Pydantic args or depends on self state"
            )
            item["pytest_output"] = (result.error_message or "")[-2000:]
            console.print(
                f"  [red]Rejected — generated stub breaks valid code[/red] "
                f"[dim](guard: {(req.raw_spec_text or '')[:50]!r})[/dim]"
            )
            console.print(
                "  [dim]Likely cause: function has Pydantic/complex args or checks self state. "
                "This is a known Quell limitation — tracked in report.[/dim]"
            )

        report_items.append(item)

    # Always write report
    _write_scan_report(project_root, str(target), all_requirements, gaps, report_items, fixed, fmt)


def _write_scaffold(
    req: Any,
    candidate: Any,
    gates_passed: int,
    config: Any,
    project_root: Path,
    item: dict[str, Any],
    scaffolded_files: set[str],
    console: Any,
    fmt: str,
) -> None:
    """Write a SCAFFOLDED stub and update item with the stub path."""
    try:
        from quell.core.scaffold import ensure_scaffold_gitignored, write_scaffold_stub
        scaffold_dir = project_root / str(config.scaffold_dir)
        stub_path = write_scaffold_stub(req, candidate, gates_passed, scaffold_dir)
        ensure_scaffold_gitignored(project_root, scaffold_dir)
        item["scaffold_file"] = str(stub_path)
        scaffolded_files.add(str(stub_path))
        if fmt != "github":
            console.print(f"  [dim]Scaffold written → {stub_path.relative_to(project_root)}[/dim]")
    except Exception:
        pass  # scaffold write is best-effort, never breaks the main flow


def _summarize_pytest_failure(out: str) -> str:
    """Pull the most informative one-liner out of pytest's --tb=short output.

    Looks for, in order: ModuleNotFoundError / ImportError / E lines / the
    short test summary info. Falls back to the last non-empty line.
    """
    if not out:
        return ""
    lines = [ln.strip() for ln in out.splitlines() if ln.strip()]
    for ln in lines:
        if ln.startswith(("ModuleNotFoundError", "ImportError", "AttributeError")):
            return ln[:180]
    for ln in lines:
        if ln.startswith("E   ") and "assert" not in ln:
            return ln[4:][:180]
    for ln in lines:
        if "Error" in ln and ":" in ln:
            return ln[:180]
    return lines[-1][:180] if lines else ""


def _write_scan_report(
    project_root: Path,
    target: str,
    all_requirements: list[Any],
    gaps: list[Any],
    items: list[dict[str, Any]],
    written: int,
    fmt: str = "console",
) -> None:
    """Write quell-report.json to project_root. Always called at end of scan."""
    import datetime
    import json

    from quell import __version__

    outcomes = [it["outcome"] for it in items]
    framework_items = [it for it in items if "framework" in it.get("type", "")]
    summary = {
        "total_requirements": len(all_requirements),
        "gaps_found": len(gaps),
        "verified_and_written": written,
        "rejected_fails_on_correct": outcomes.count("rejected_fails_on_correct"),
        "rejected_no_catch": outcomes.count("rejected_no_catch"),
        "skipped_no_rule": outcomes.count("skipped_no_rule"),
        "skipped_async": outcomes.count("skipped_async"),
        "skipped_local_var": outcomes.count("skipped_local_var"),
        "skipped_no_gen": outcomes.count("skipped_no_gen"),
        "framework_routes_detected": len(framework_items),
        "skipped_framework_no_app": outcomes.count("skipped_framework_no_app"),
        "skipped_framework_unsupported": outcomes.count("skipped_framework_unsupported"),
    }
    report = {
        "quell_version": __version__,
        "timestamp": datetime.datetime.now(datetime.UTC).isoformat(),
        "target": target,
        "summary": summary,
        "results": items,
    }
    report_path = project_root / "quell-report.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    if fmt == "github":
        # In GitHub Actions mode, only emit machine-readable output to stdout.
        # The report path is available via the action's output variable.
        return

    # ── Three-bucket display (spec7 §2.3) ─────────────────────────────────────
    scaffolded_outcomes = {
        "skipped_no_rule", "skipped_local_var", "skipped_async", "skipped_no_gen",
    }
    written_outcomes = {"verified_and_written", "written"}

    written_items = [it for it in items if it.get("outcome") in written_outcomes]
    scaffolded_items = [it for it in items if it.get("outcome") in scaffolded_outcomes]
    flagged_items = [
        it for it in items
        if it.get("outcome") not in (written_outcomes | scaffolded_outcomes)
    ]

    total_edge_cases = max(len(gaps) if gaps else len(items), 1)
    default_rule_confidence = 80
    prs_raw = int(len(written_items) * default_rule_confidence / (total_edge_cases * 100) * 100)
    prs_score = max(0, min(100, prs_raw))
    if prs_score >= 80:
        prs_tier, prs_label = "green", "Production Ready"
    elif prs_score >= 60:
        prs_tier, prs_label = "yellow", "Review Needed"
    else:
        prs_tier, prs_label = "red", "Edge Cases Uncovered"

    from quell.ui.console import render_bucketed_summary
    render_bucketed_summary(
        written=[
            {
                "file": it.get("file", ""),
                "confidence": default_rule_confidence,
                "tier": "HIGH" if default_rule_confidence >= 85 else "MEDIUM",
                "requirement_id": f"{it.get('function', '')}@{it.get('type', '')}",
            }
            for it in written_items
        ],
        scaffolded=[
            {"scaffold_file": it.get("file", ""), "source_file": it.get("file", "")}
            for it in scaffolded_items
        ],
        flagged=[
            {
                "source_file": it.get("file", ""),
                "source_line": it.get("line"),
                "reason": it.get("reason") or it.get("outcome", "unknown"),
            }
            for it in flagged_items
        ],
        prs_score=prs_score,
        prs_tier=prs_tier,
        prs_tier_label=prs_label,
        avg_confidence=float(default_rule_confidence) if written_items else 0.0,
        total=total_edge_cases,
        report_path=str(report_path),
    )

    if summary["rejected_fails_on_correct"] > 0:
        console.print(
            "  [dim]Tip: share quell-report.json with the Quell maintainer "
            "so these complex function patterns can be supported.[/dim]"
        )


@app.command("check")
def cmd_check(  # noqa: PLR0913
    target: str = typer.Argument(".", help="File or directory to check"),
    fix: bool = typer.Option(False, "--fix", help="Generate and write verified tests"),
    no_llm: bool = typer.Option(
        False, "--no-llm",
        help="Disable all LLM calls. Rule-based only. No network. Default for CI.",
    ),
    sources: str | None = typer.Option(
        None, "--sources", help="Comma-separated: docstring,type,mutation"
    ),
    fmt: str = typer.Option("console", "--format", "-f", help="Output format: console or json"),
    project_root: Path = typer.Option(Path("."), "--root", help="Project root"),
    with_containers: bool = typer.Option(
        False, "--with-containers",
        help="Auto-detect infra deps and spin up ephemeral containers",
    ),
    min_confidence: int = typer.Option(
        50, "--min-confidence",
        help="Only write tests at or above this confidence score (0-100)",
        min=0, max=100,
    ),
    ci_confidence: int = typer.Option(
        70, "--ci-confidence",
        help="CI enforcement threshold — tests below this are review-only",
        min=0, max=100,
    ),
    keep_containers: bool = typer.Option(
        False, "--keep-containers",
        help="Keep containers alive after the run (reused on next quell check)",
    ),
    show_why: bool = typer.Option(
        False, "--show-why",
        help="Print the dependency path explaining why each container is started",
    ),
    graph_rebuild: bool = typer.Option(
        False, "--graph-rebuild",
        help="Force a full QuellGraph rebuild before scanning",
    ),
) -> None:
    """
    [deprecated] Use `quell find` instead. Will be removed in v2.2.

    Check requirement coverage from type annotations and docstrings.
    """
    import sys as _sys
    _sys.stderr.write(
        "[quell] DEPRECATED: `quell check` has been renamed to `quell find`. "
        "It will be removed in v2.2. Run `quell find` instead.\n"
    )
    from quell.sdk import Quell

    src_list = sources.split(",") if sources else ["docstring", "type"]
    config = _load_config(project_root)
    if no_llm:
        config = config.model_copy(update={"llm_provider": "none"})

    # QuellGraph: build or rebuild before scanning if requested
    graph_db = project_root / ".quellgraph" / "graph.db"
    if graph_rebuild or (with_containers and not graph_db.exists()):
        from quell.graph.builder import QuellGraphBuilder
        with console.status("[bold blue]Building QuellGraph...[/bold blue]"):
            builder = QuellGraphBuilder(graph_db)
            report = builder.build(project_root)
            console.print(
                f"[dim]QuellGraph: {report.total_files} files "
                f"({report.reparsed} reparsed, "
                f"{report.total_files - report.reparsed} cached)  "
                f"{report.functions} functions  {report.classes} classes[/dim]"
            )

    # Container engine: spin up ephemeral containers when requested
    container_engine = None
    if with_containers:
        from quell.infra.engine import ContainerEngine
        container_engine = ContainerEngine(
            lock_path=project_root / ".quellgraph" / "containers.lock"
        )
        if graph_db.exists():
            from quell.graph.query import QuellGraph
            try:
                graph = QuellGraph(graph_db)
                stats = graph.stats()
                if stats.get("infra_dependent", 0) > 0:
                    # Collect all infra tags across functions that need containers
                    all_tags: set[str] = set()
                    for fn in graph.list_functions():
                        all_tags.update(graph.get_transitive_infra_tags(fn.id))

                    if show_why and all_tags:
                        console.print(
                            f"[dim]Containers needed: {', '.join(sorted(all_tags))}[/dim]"
                        )

                    with console.status(
                        f"[bold blue]Starting containers: {', '.join(sorted(all_tags))}...[/bold blue]"
                    ):
                        container_engine.prepare(all_tags)
            except Exception as exc:
                console.print(f"[yellow]QuellGraph unavailable: {exc}[/yellow]")

    q = Quell(project_root=project_root)

    with console.status("[bold blue]Scanning specifications...[/bold blue]"):
        result = q.check(target, sources=src_list, fix=fix)

    # Teardown containers unless --keep-containers was passed
    if container_engine is not None and not keep_containers:
        torn = container_engine.teardown()
        if torn:
            console.print(f"[dim]Containers stopped: {', '.join(torn)}[/dim]")

    if fmt == "json":
        gaps = [
            {
                "file": r.target_file.name,
                "function": r.target_function,
                "description": r.description,
                "kind": r.constraint_kind.value,
                "source": r.source.value,
            }
            for r in result.requirements if not r.is_covered
        ]
        output = {
            "quell_version": __version__,
            "target": target,
            "total_requirements": len(result.requirements),
            "covered": len(result.covered),
            "gaps": gaps,
            "score": result.score,
        }
        print(_json.dumps(output, indent=2))
        return

    table = Table(title=f"Requirements — {target}", show_header=True)
    table.add_column("Function", style="cyan")
    table.add_column("Kind", style="yellow")
    table.add_column("Description")
    table.add_column("Covered", style="green")
    table.add_column("Method")

    for req in result.requirements:
        covered = "YES" if req.is_covered else "NO"
        style = "green" if req.is_covered else "red"
        tag = _method_tag(req.source.value)
        table.add_row(
            req.target_function,
            req.constraint_kind.value,
            req.description[:55] + ("..." if len(req.description) > 55 else ""),
            f"[{style}]{covered}[/{style}]",
            tag,
        )

    console.print(table)
    console.print(
        f"\n[bold]Score:[/bold] {result.score:.0%} "
        f"({len(result.covered)}/{len(result.requirements)} covered)"
    )

    if result.uncovered:
        console.print(
            f"\n[yellow]{len(result.uncovered)} gap(s) found.[/yellow]"
            + (" Run with --fix to generate tests." if not fix else "")
        )

    if fix and result.report_path:
        console.print(
            f"\n[bold]Diagnostic report:[/bold] {result.report_path}\n"
            "[dim]Share this file with the Quell maintainer to improve "
            "rule engine coverage. No source code is included.[/dim]"
        )
        # Check if any verified test was LLM-generated
        llm_used = False
        try:
            rpt = _json.loads(result.report_path.read_text())
            llm_used = any(
                o.get("generated_by", "").startswith("llm")
                for o in rpt.get("outcomes", [])
                if o.get("outcome") == "verified"
            )
        except Exception:
            pass
        if not llm_used:
            console.print("\n[dim]Your code never left your machine.[/dim]")
        else:
            console.print(
                "\n[dim]LLM used for complex cases. "
                "Only function signatures were sent — never business logic.[/dim]"
            )

    if not result.requirements:
        console.print(
            "\n[dim]No requirements found. Add docstrings with Raises:/Returns: "
            "blocks or Pydantic Field constraints.[/dim]"
        )
        console.print(
            "[dim]No API key needed for rule-based checks. "
            "For LLM features: quell auth login[/dim]"
        )


@app.command("reproduce")
def cmd_reproduce(
    description: str = typer.Argument(..., help="Bug description in plain English"),
    file: str | None = typer.Option(None, "--file", help="Target source file"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Convert a bug description into a verified failing test."""
    from quell.sdk import Quell

    q = Quell(project_root=project_root)

    with console.status("[bold blue]Analyzing bug description...[/bold blue]"):
        written = q.reproduce(description, file=file)

    if written:
        console.print(Panel(
            "[green]Bug reproduction test written.[/green]\n"
            "The test currently FAILS (bug exists). Fix the code, then run it to confirm.",
            title="quell reproduce",
        ))
    else:
        console.print("[red]Could not generate a verified bug reproduction test.[/red]")
        raise typer.Exit(1)


@app.command("prove")
def cmd_prove(
    file: str = typer.Argument(..., help="Source file to prove"),
    function: str | None = typer.Option(None, "--function", help="Specific function"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Show requirement coverage score for a file or function."""
    from quell.sdk import Quell

    q = Quell(project_root=project_root)

    with console.status("[bold blue]Checking coverage...[/bold blue]"):
        score = q.prove(file, function=function)

    color = "green" if score >= 0.80 else "yellow" if score >= 0.60 else "red"
    label = f"{function or file}"
    console.print(
        Panel(
            f"[{color}]{score:.0%}[/{color}] of requirements proven for [cyan]{label}[/cyan]",
            title="Quell Score",
        )
    )


@app.command("score")
def cmd_score(
    target: Path = typer.Argument(Path("."), help="File or directory to score"),
    badge: bool = typer.Option(False, "--badge", help="Print SVG badge to stdout"),
    json_out: bool = typer.Option(False, "--json", help="Output score as JSON"),
    sync: bool = typer.Option(False, "--sync", help="Push PRS snapshot to cloud (Pro/Team only)"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Show Production Readiness Score (PRS) for a path.

    Reads cached .quell/quell-report.json when available.
    Falls back to a live scan if no cached report exists.

    quell score src/              # show PRS for src/
    quell score src/ --badge      # print SVG badge to stdout
    quell score src/ --json       # JSON output for scripts
    """
    import json as _json

    from quell.core.confidence.badge import generate_badge
    from quell.core.confidence.prs import PRSResult, compute_prs

    # Try reading cached report first
    report_path = project_root / "quell-report.json"
    prs: PRSResult | None = None

    if report_path.exists():
        try:
            data = _json.loads(report_path.read_text(encoding="utf-8"))
            # Bucketed report format has written_count / flagged_count
            if "written_count" in data and "flagged_count" in data:
                from quell.core.models import BucketedResult, ConfidenceTier, FlagReason, OutputBucket
                results: list[BucketedResult] = []
                for item in data.get("written", []):
                    conf = item.get("confidence") or 80
                    tier_str = (item.get("tier") or "MEDIUM").upper()
                    tier = ConfidenceTier(tier_str) if tier_str in ("HIGH", "MEDIUM", "LOW") else ConfidenceTier.MEDIUM
                    results.append(BucketedResult(
                        requirement_id=item.get("requirement_id", ""),
                        bucket=OutputBucket.WRITTEN,
                        gates_passed=5,
                        confidence_score=conf,
                        confidence_tier=tier,
                    ))
                for item in data.get("scaffolded", []):
                    results.append(BucketedResult(
                        requirement_id=item.get("requirement_id", ""),
                        bucket=OutputBucket.SCAFFOLDED,
                        gates_passed=3,
                    ))
                for item in data.get("flagged", []):
                    raw_reason = item.get("reason", "unknown")
                    flag_reason: FlagReason | None = None
                    for fr in FlagReason:
                        if fr.value == raw_reason:
                            flag_reason = fr
                            break
                    results.append(BucketedResult(
                        requirement_id=item.get("requirement_id", ""),
                        bucket=OutputBucket.FLAGGED,
                        flag_reason=flag_reason,
                        gates_passed=0,
                    ))
                prs = compute_prs(results)
        except Exception:
            prs = None

    if prs is None:
        # Fall back to live scan (no --fix, just reading)
        console.print("[dim]No cached report found — running a quick scan...[/dim]")
        from quell.core.confidence.prs import compute_prs as _compute_prs
        from quell.core.models import BucketedResult, OutputBucket
        from quell.coverage.checker import CoverageChecker
        from quell.spec.code_guard_reader import CodeGuardReader
        from quell.synthesis.rule_engine import RuleEngine

        files = (
            [f for f in target.rglob("*.py")
             if "test" not in f.name and ".venv" not in str(f) and "__pycache__" not in str(f)]
            if target.is_dir() else [target]
        )
        reader = CodeGuardReader()
        checker = CoverageChecker(project_root)
        engine = RuleEngine()
        all_reqs = []
        for f in files:
            all_reqs.extend(reader.read(f))
        checked = checker.check(all_reqs)
        gaps = [r for r in checked if not r.is_covered]

        scan_results: list[BucketedResult] = []
        for req in gaps:
            test = engine.generate(req)
            if test is not None:
                scan_results.append(BucketedResult(
                    requirement_id=req.id,
                    bucket=OutputBucket.WRITTEN,
                    gates_passed=5,
                    confidence_score=80,
                ))
            else:
                scan_results.append(BucketedResult(
                    requirement_id=req.id,
                    bucket=OutputBucket.SCAFFOLDED,
                    gates_passed=3,
                ))
        prs = _compute_prs(scan_results)

    if json_out:
        import json as _json2
        from dataclasses import asdict
        print(_json2.dumps(asdict(prs), indent=2))
        return

    if badge:
        svg = generate_badge(prs.score, prs.tier)
        print(svg)
        return

    tier_color = {"green": "green", "yellow": "yellow", "red": "red"}.get(prs.tier, "white")
    tier_emoji = {"green": "🟢", "yellow": "🟡", "red": "🔴"}.get(prs.tier, "")

    console.print(Panel.fit(
        f"[bold]PRS  [{tier_color}]{prs.score}/100[/{tier_color}][/bold]  "
        f"{tier_emoji} [{tier_color}]{prs.tier_label}[/{tier_color}]\n\n"
        f"  Edge case coverage : {prs.edge_case_coverage_pct:.0f}%\n"
        f"  WRITTEN            : {prs.written_count}\n"
        f"  SCAFFOLDED         : {prs.scaffolded_count}\n"
        f"  FLAGGED            : {prs.flagged_count}\n"
        f"  Avg confidence     : {prs.avg_written_confidence:.0f}%"
        + (f"\n\n  [dim]Modifiers: {', '.join(prs.modifiers)}[/dim]" if prs.modifiers else ""),
        title="quell score",
    ))

    if sync:
        _do_sync(project_root)


@app.command("ci")
def cmd_ci(
    target: str = typer.Argument(".", help="File or directory to check"),
    threshold: float = typer.Option(0.0, "--threshold", help="Minimum score (0.0–1.0)"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """CI mode: check requirements and exit 1 if below threshold."""
    from quell.sdk import Quell

    q = Quell(project_root=project_root)
    result = q.check(target)

    console.print(f"Quell Score: {result.score:.0%} | Threshold: {threshold:.0%}")

    if result.score < threshold:
        console.print(
            f"[red]FAIL: {result.score:.0%} < {threshold:.0%} threshold[/red]"
        )
        raise typer.Exit(1)

    console.print("[green]PASS[/green]")


@app.command("init")
def cmd_init(
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Add [tool.quell] configuration block to pyproject.toml."""
    pyproject = project_root / "pyproject.toml"

    if not pyproject.exists():
        console.print("[red]No pyproject.toml found. Create one first.[/red]")
        raise typer.Exit(1)

    content = pyproject.read_text()
    if "[tool.quell]" in content:
        console.print("[yellow][tool.quell] already exists in pyproject.toml[/yellow]")
        return

    quell_block = """
[tool.quell]
llm_provider = "groq"
llm_model = "llama-3.3-70b-versatile"
use_llm = false
max_verification_attempts = 3
verification_timeout_seconds = 30
auto_write = false
prs_threshold = 60
scaffold_dir = "tests/scaffold"
enable_docstring = true
enable_types = true
enable_mutations = false
enable_pyspark = false
"""
    pyproject.write_text(content + quell_block)
    console.print("[green]Added [tool.quell] to pyproject.toml[/green]")
    console.print("  LLM fallback is off by default (use_llm = false).")
    console.print("  To enable: [bold]quell auth set --provider groq --key sk-...[/bold]")

    from quell.core.scaffold import ensure_scaffold_gitignored
    scaffold_dir_path = project_root / "tests" / "scaffold"
    ensure_scaffold_gitignored(project_root, scaffold_dir_path)
    console.print(f"  Scaffold dir added to .gitignore: [dim]{scaffold_dir_path.relative_to(project_root)}[/dim]")


@app.command("pr")
def cmd_pr(
    pr_number: int = typer.Argument(..., help="Pull request number to analyze"),
    repo: str = typer.Option("", "--repo", "-r", help="owner/repo (auto-detected from git remote)"),
    token: str = typer.Option("", "--token", "-t", help="GitHub token (or set GITHUB_TOKEN env var)"),
    fix: bool = typer.Option(False, "--fix", help="Generate + write missing tests locally"),
    comment: bool = typer.Option(False, "--comment", "-c", help="Post result as PR comment"),
    fmt: str = typer.Option("console", "--format", "-f", help="console or json"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """
    Analyze requirement coverage for a GitHub Pull Request.

    Examples:
      quell pr 42                     # show gaps for PR #42
      quell pr 42 --comment           # post report as PR comment
      quell pr 42 --fix               # generate missing tests locally
      quell pr 42 --repo owner/repo   # specify repo explicitly
      quell pr 42 --format json       # JSON output (for CI)

    Authentication:
      Set GITHUB_TOKEN environment variable, or use --token flag.
      Get token: github.com/settings/tokens (needs repo + pull_requests scope)
    """
    from quell.github.pr_runner import GitHubPRRunner

    config = _load_config(project_root)

    runner = GitHubPRRunner(
        pr_number=pr_number,
        repo=repo or None,
        token=token or None,
        project_root=project_root,
    )

    with console.status(f"[bold blue]Fetching PR #{pr_number} from GitHub...[/bold blue]"):
        try:
            report = runner.run_quell_on_pr(config)
        except Exception as e:
            console.print(f"[red]Error fetching PR: {e}[/red]")
            console.print("\nTroubleshooting:")
            console.print("  Set GITHUB_TOKEN env var (needs repo read access)")
            console.print("  Use --repo owner/reponame to specify the repo")
            console.print("  Get a token: github.com/settings/tokens")
            raise typer.Exit(1)

    if fmt == "json":
        print(_json.dumps(report, indent=2))
        return

    score = report["score"]
    emoji = "\U0001f7e2" if score >= 0.8 else "\U0001f7e1" if score >= 0.5 else "\U0001f534"

    console.print(Panel.fit(
        f"{emoji} [bold]PR #{report['pr_number']}[/bold]: {report['pr_title']}\n"
        f"Author: @{report.get('pr_author', 'unknown')}\n"
        f"Changed files: {len(report['changed_files'])}\n"
        f"Requirements: {report['total_requirements']} found, "
        f"{len(report['gaps'])} untested",
        title="Quell PR Analysis",
    ))

    if not report["gaps"]:
        console.print("[green]All requirements in changed files are tested.[/green]")
    else:
        table = Table(title=f"{len(report['gaps'])} Untested Requirements")
        table.add_column("File", style="blue")
        table.add_column("Function", style="cyan")
        table.add_column("Requirement", style="white")
        table.add_column("Type", style="magenta")

        for g in report["gaps"]:
            table.add_row(g["file"], g["function"], g["description"], g["kind"])

        console.print(table)
        console.print("\n[yellow]Fix locally:[/yellow] quell check src/ --fix")

    if comment:
        with console.status("Posting comment to PR..."):
            try:
                runner.post_comment(report)
                console.print(f"[green]Comment posted to PR #{pr_number}[/green]")
                console.print(f"  {report.get('pr_url', '')}")
            except Exception as e:
                console.print(f"[red]Failed to post comment: {e}[/red]")
                raise typer.Exit(1)


@app.command("install")
def cmd_install(
    project_root: Path = typer.Option(Path("."), "--root"),
    hook: bool = typer.Option(False, "--hook", help="Add pre-commit hook"),
    pr: bool = typer.Option(False, "--pr", help="Add GitHub Actions PR workflow"),
) -> None:
    """
    Set up Quell in your project.

    quell install          → adds both pre-commit hook and GitHub Action
    quell install --hook   → pre-commit hook only
    quell install --pr     → GitHub Action only
    """
    if not hook and not pr:
        hook = True
        pr = True

    if hook:
        _install_precommit_hook(project_root)

    if pr:
        _install_github_action(project_root)


def _install_precommit_hook(project_root: Path) -> None:
    config_file = project_root / ".pre-commit-config.yaml"
    hook_entry = """
  - repo: local
    hooks:
      - id: quell
        name: Quell — verify requirements
        entry: quell check --diff-only --no-llm --auto
        language: system
        types: [python]
        pass_filenames: false
"""
    if config_file.exists():
        if "id: quell" in config_file.read_text():
            console.print("[yellow]Quell hook already in .pre-commit-config.yaml[/yellow]")
            return
        config_file.write_text(config_file.read_text() + hook_entry)
    else:
        config_file.write_text(f"repos:{hook_entry}")

    console.print("[green]Added Quell to .pre-commit-config.yaml[/green]")
    console.print("  Runs on every git commit (changed files only, < 3 seconds)")


def _install_github_action(project_root: Path) -> None:
    workflows_dir = project_root / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)
    action_file = workflows_dir / "quell.yml"

    if action_file.exists():
        console.print("[yellow]quell.yml already in .github/workflows/[/yellow]")
        return

    action_file.write_text(GITHUB_ACTION_YAML)
    console.print("[green]Created .github/workflows/quell.yml[/green]")
    console.print("\nNext steps:")
    console.print("  1. Add QUELL_API_KEY to GitHub repo secrets")
    console.print("     github.com → Settings → Secrets → Actions")
    console.print("     Get key: quell.buildsbyshashank.tech")
    console.print("\n  2. git add .github/workflows/quell.yml && git commit")
    console.print("\n  Quell will comment on every PR automatically.")


# ── Teardown command ─────────────────────────────────────────────────────────


@app.command("teardown")
def cmd_teardown(
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Stop and remove all quelltest-managed ephemeral containers."""
    from quell.infra.engine import ContainerEngine

    engine = ContainerEngine(
        lock_path=project_root / ".quellgraph" / "containers.lock"
    )
    torn = engine.teardown()
    if torn:
        console.print(f"[green]Stopped containers: {', '.join(torn)}[/green]")
    else:
        console.print("[dim]No running quelltest containers found.[/dim]")


@app.command("mcp")
def cmd_mcp() -> None:
    """Run the local MCP server (stdio) so AI agents can operate Quelltest.

    Register in your project's .mcp.json:
        {"mcpServers": {"quelltest": {"command": "quelltest-mcp"}}}
    """
    from quell.mcp_server import main as mcp_main

    mcp_main()


# ── Graph subcommands ─────────────────────────────────────────────────────────


def _require_graph(project_root: Path):
    """Return a QuellGraph or exit with a helpful message."""
    from quell.graph.query import QuellGraph

    db = project_root / ".quellgraph" / "graph.db"
    if not db.exists():
        console.print(
            "[yellow]No QuellGraph found. Run [bold]quell graph build[/bold] first.[/yellow]"
        )
        raise typer.Exit(1)
    return QuellGraph(db)


@graph_app.command("build")
def graph_build(
    src: Path = typer.Argument(Path("."), help="Source directory to index"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Build or incrementally update the QuellGraph code-intelligence index."""
    from quell.graph.builder import QuellGraphBuilder

    db = project_root / ".quellgraph" / "graph.db"
    builder = QuellGraphBuilder(db)

    with console.status(f"[bold blue]Building QuellGraph from {src}...[/bold blue]"):
        report = builder.build(src if src != Path(".") else project_root)

    console.print(
        f"[green]QuellGraph built.[/green]  "
        f"{report.total_files} files  "
        f"({report.reparsed} reparsed, {report.total_files - report.reparsed} cached)  "
        f"{report.functions} functions  {report.classes} classes  "
        f"[dim]{report.build_time_ms}ms[/dim]"
    )


@graph_app.command("show")
def graph_show(
    file: str | None = typer.Argument(None, help="Specific .py file to show (default: all)"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Print functions, infra tags, annotation coverage, and confidence preview."""
    graph = _require_graph(project_root)

    fns = graph.list_functions(file=file) if file else graph.list_functions()
    if not fns:
        console.print("[dim]No functions indexed.[/dim]")
        return

    current_file = None
    for fn in fns:
        if fn.file != current_file:
            current_file = fn.file
            console.print(f"\n[bold blue]{fn.file}[/bold blue]")

        tags = graph.get_transitive_infra_tags(fn.id)
        tag_str = f"[{', '.join(sorted(tags))}]" if tags else "[]"
        ann_pct = int(fn.annotation_coverage * 100)
        param_typed = round(fn.annotation_coverage * (fn.param_count + 1))
        total_slots = fn.param_count + 1
        conf_approx = round(fn.annotation_coverage * 25 + (10 if fn.has_docstring else 0))
        console.print(
            f"  [cyan]{fn.name}[/cyan]  {tag_str}  "
            f"annotations: {param_typed}/{total_slots} ({ann_pct}%)  "
            f"purity: {fn.purity_score:.1f}  "
            f"[dim]conf: ~{conf_approx}[/dim]"
        )


@graph_app.command("why")
def graph_why(
    function: str = typer.Argument(..., help="Function name to explain"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Print the call path explaining why a container dependency is needed."""
    graph = _require_graph(project_root)

    fns = [fn for fn in graph.list_functions() if fn.name == function]
    if not fns:
        console.print(f"[yellow]Function '{function}' not found in QuellGraph.[/yellow]")
        raise typer.Exit(1)

    fn = fns[0]
    tags = graph.get_transitive_infra_tags(fn.id)
    if not tags:
        console.print(f"[green]{function}[/green] has no infra dependencies — pure function.")
        return

    console.print(f"[cyan]{function}[/cyan] needs: {', '.join(sorted(tags))}")
    path = graph.get_infra_dependency_path(fn.id)
    if path:
        console.print("  " + " → ".join(path))
    else:
        console.print("  [dim](dependency path not traced — direct import)[/dim]")


@graph_app.command("stale")
def graph_stale(
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Show functions whose generated tests may be stale after recent changes."""
    import subprocess

    graph = _require_graph(project_root)

    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "HEAD"],
            capture_output=True, text=True, cwd=project_root,
        )
        changed = [f for f in result.stdout.splitlines() if f.endswith(".py")]
    except Exception:
        console.print("[yellow]Could not detect changed files (not a git repo?).[/yellow]")
        changed = []

    if not changed:
        console.print("[green]No changed Python files detected.[/green]")
        return

    stale_ids = graph.find_stale_tests(changed)
    if not stale_ids:
        console.print("[green]No stale tests detected.[/green]")
        return

    console.print(f"[yellow]{len(stale_ids)} function(s) may have stale tests:[/yellow]")
    for fn_id in stale_ids:
        fn = graph.get_function_by_id(fn_id)
        if fn:
            console.print(f"  [cyan]{fn.name}[/cyan]  ({fn.file})")


@graph_app.command("stats")
def graph_stats(
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Print summary stats: functions, classes, infra-dependent, pure."""
    graph = _require_graph(project_root)
    s = graph.stats()

    table = Table(title="QuellGraph Stats")
    table.add_column("Metric")
    table.add_column("Count", justify="right")

    table.add_row("Total functions", str(s.get("functions", 0)))
    table.add_row("Total classes", str(s.get("classes", 0)))
    table.add_row("Infra-dependent functions", str(s.get("infra_dependent", 0)))
    table.add_row("Pure functions", str(s.get("pure", 0)))

    console.print(table)


# ── Auth subcommands ──────────────────────────────────────────────────────────

@auth_app.command("login")
def auth_login() -> None:
    """
    Log in to quell.buildsbyshashank.tech via browser.

    Opens your browser for secure OAuth login.
    One active session per account — logging in here
    invalidates any other active sessions.

    For CI/CD: set QUELL_API_KEY environment variable instead.
    """
    from quell.auth.oauth import login

    try:
        with console.status("Waiting for browser login..."):
            credentials = login()

        email = credentials.get("email", "unknown")
        plan = credentials.get("plan", "free").capitalize()

        console.print(f"\n[green]Logged in as {email}[/green]")
        console.print(f"  Plan: {plan}")
        console.print("  Session: active on this device")
        console.print("\n  Rule-based checks: unlimited, always free")
        console.print("  LLM checks: use --llm flag (rate limited by plan)")
        console.print("\n  [dim]Previous sessions on other devices have been revoked.[/dim]")

    except RuntimeError as e:
        console.print(f"[red]Login failed: {e}[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]Unexpected error: {e}[/red]")
        console.print("Try again or report at: github.com/shashank7109/quell/issues")
        raise typer.Exit(1)


@auth_app.command("logout")
def auth_logout() -> None:
    """Log out and revoke your session token."""
    from quell.auth.oauth import load_credentials, logout

    creds = load_credentials()
    if not creds:
        console.print("[yellow]Not logged in.[/yellow]")
        return

    with console.status("Revoking session..."):
        logout()

    console.print("[green]Logged out. Token revoked on server.[/green]")
    console.print("  Run [bold]quell auth login[/bold] to log in again.")


@auth_app.command("set")
def auth_set(
    provider: str = typer.Option(..., "--provider", help="Provider: groq, quell, anthropic, openai"),
    key: str = typer.Option("", "--key", help="API key (omit to use quell-managed auth)"),
) -> None:
    """Configure a LLM provider API key.

    quell auth set --provider groq --key sk-...    # BYO Groq key
    quell auth set --provider quell               # Use Quell-managed (Pro)
    quell auth set --provider anthropic --key sk-ant-...
    """
    from quell.auth.storage import AuthMode, save_credentials

    mode: AuthMode = "byo" if key else "quell"
    try:
        save_credentials(
            provider=provider,  # type: ignore[arg-type]
            mode=mode,
            key=key,
        )
    except Exception as exc:
        console.print(f"[red]Failed to save credentials: {exc}[/red]")
        raise typer.Exit(1)

    if key:
        console.print(f"[green]BYO key saved for provider '{provider}'.[/green]")
        console.print("  Your code never leaves your machine in rule-based mode.")
        console.print("  LLM fallback sends only function signature + docstring.")
    else:
        console.print(f"[green]Configured to use Quell-managed '{provider}' (Pro).[/green]")
        console.print("  Run [bold]quell auth login[/bold] to authenticate.")


@auth_app.command("status")
def auth_status_v2(
    privacy: bool = typer.Option(False, "--privacy", help="Show what data is sent per mode"),
) -> None:
    """Show current Quell auth status and configured provider.

    quell auth status            # show provider, tier, key validity
    quell auth status --privacy  # print exactly what leaves your machine
    """
    from quell.auth.storage import load_credentials, resolve_key

    if privacy:
        console.print("[bold]Privacy statement — what leaves your machine:[/bold]\n")
        console.print(
            "  [green]Rule-based mode (no auth):[/green]\n"
            "    Zero network calls. Code never leaves your machine.\n"
            "    All analysis is local AST scanning.\n"
        )
        console.print(
            "  [yellow]BYO key (groq/anthropic/openai):[/yellow]\n"
            "    Sent to provider: function signature + docstring + spec text only.\n"
            "    Never sent: full source files, test code, secrets, env vars.\n"
        )
        console.print(
            "  [blue]Quell-managed (Pro):[/blue]\n"
            "    Same as BYO key, routed through quell.buildsbyshashank.tech proxy.\n"
            "    Quell does not log your code.\n"
        )
        return

    creds = load_credentials()
    if not creds or creds.provider == "none":
        console.print("[yellow]No auth configured.[/yellow]")
        console.print("  Rule-based checks work without auth (free tier).")
        console.print("  To add a key: [bold]quell auth set --provider groq --key sk-...[/bold]")
        return

    key = resolve_key(creds)
    key_status = "[green]valid[/green]" if key else "[yellow]not found[/yellow]"

    console.print(f"  Provider : [bold]{creds.provider}[/bold]")
    console.print(f"  Mode     : {creds.mode}")
    console.print(f"  Tier     : {creds.tier}")
    console.print(f"  Key      : {key_status}")


# ── Cloud Sync helpers and commands (spec8 §11.3) ─────────────────────────────

def _do_sync(project_root: Path) -> None:
    """Shared sync logic called from --sync flag on find/score."""
    from quell.auth.storage import load_credentials
    from quell.sync.client import push_report
    from quell.sync.payload import build_sync_payload
    from quell.sync.sanitizer import SanitizationError, sanitize

    creds = load_credentials()
    tier = getattr(creds, "tier", "free") if creds else "free"
    if tier == "free":
        console.print("[yellow]Sync requires a Pro or Team account.[/yellow]")
        console.print("  Upgrade at [bold]quelltest.com/pricing[/bold]")
        return

    report_path = project_root / ".quell" / "report.json"
    if not report_path.exists():
        # fall back to quell-report.json at root
        report_path = project_root / "quell-report.json"

    config = _load_config(project_root)
    payload = build_sync_payload(
        report_path=report_path,
        project_root=project_root,
        project_alias=config.sync_project_alias,
    )
    if payload is None:
        console.print("[yellow]Sync: no report found. Run quell find first.[/yellow]")
        return

    try:
        sanitize(payload.model_dump(mode="json"))
    except SanitizationError as exc:
        console.print(f"[red]Sync aborted: {exc}[/red]")
        return

    result = push_report(payload)
    if result.ok:
        console.print(f"[green]Report synced -> {result.dashboard_url}[/green]")
    else:
        console.print(f"[yellow]Sync warning: {result.reason}[/yellow]")


@sync_app.command("push")
def sync_push(
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Manually push the last .quell/report.json to quelltest.com."""
    _do_sync(project_root)


@sync_app.command("status")
def sync_status(
    privacy: bool = typer.Option(False, "--privacy", help="Show exactly what gets sent"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Show cloud sync state, last push timestamp, and tier.

    quell sync status            # show sync state
    quell sync status --privacy  # print what leaves your machine
    """
    import json as _j

    from quell.auth.storage import load_credentials

    config = _load_config(project_root)
    creds = load_credentials()
    tier = getattr(creds, "tier", "free") if creds else "free"

    sync_enabled = config.sync or (tier != "free")

    if privacy:
        console.print("[bold]Sync privacy statement:[/bold]\n")
        console.print(f"  Sync enabled : {'yes' if sync_enabled else 'no'} ({tier} tier)")
        console.print(f"  Project      : {config.sync_project_alias or project_root.resolve().name}")
        console.print("  What gets sent:")
        console.print("    - test names, confidence scores, flagged reasons")
        console.print("    - PRS, file:line locations for flagged items")
        console.print("  What stays local:")
        console.print("    - all source code, all test bodies, all docstrings")
        console.print("  Full schema: https://quelltest.com/docs/sync-payload")
        return

    history_file = project_root / ".quell" / "sync_history.json"
    last_push = "never"
    if history_file.exists():
        try:
            history = _j.loads(history_file.read_text())
            if history:
                last_push = history[-1].get("run_at", "unknown")
        except Exception:  # noqa: BLE001
            pass

    console.print(f"  Sync enabled : {'yes' if sync_enabled else 'no'} ({tier} tier)")
    console.print(f"  Project alias: {config.sync_project_alias or '(not set)'}")
    console.print(f"  Last push    : {last_push}")
    if not sync_enabled:
        console.print("\n  To enable: add [dim]sync = true[/dim] to [tool.quell] in pyproject.toml")
        console.print("  or use [dim]--sync[/dim] flag on quell find / quell score")


@sync_app.command("history")
def sync_history(
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """List the last 30 sync pushes with PRS values."""
    import json as _j

    history_file = project_root / ".quell" / "sync_history.json"
    if not history_file.exists():
        console.print("[yellow]No sync history found.[/yellow]")
        console.print("  Run [bold]quell find --sync[/bold] to create one.")
        return

    try:
        history = _j.loads(history_file.read_text())
    except Exception:  # noqa: BLE001
        console.print("[red]Could not read sync history.[/red]")
        return

    table = Table(title="Sync History (last 30 pushes)")
    table.add_column("Run at", style="dim")
    table.add_column("PRS", justify="right")
    table.add_column("Project")

    for entry in history[-30:][::-1]:
        prs = entry.get("prs", "-")
        color = "green" if prs >= 80 else "yellow" if prs >= 60 else "red"
        table.add_row(
            entry.get("run_at", "-"),
            f"[{color}]{prs}[/{color}]",
            entry.get("project_id", "-")[:16] + "...",
        )
    console.print(table)


@sync_app.command("unlink")
def sync_unlink(
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation prompt"),
    project_root: Path = typer.Option(Path("."), "--root"),
) -> None:
    """Remove this project from quelltest.com and delete all remote data."""
    import json as _j

    from quell.sync.client import _load_token

    config = _load_config(project_root)
    alias = config.sync_project_alias or project_root.resolve().name

    if not yes:
        confirmed = typer.confirm(
            f"Delete all cloud data for '{alias}'? This cannot be undone."
        )
        if not confirmed:
            console.print("Aborted.")
            return

    token = _load_token()
    if not token:
        console.print("[red]Not authenticated. Run `quell auth login` first.[/red]")
        raise typer.Exit(1)

    try:
        import httpx

        from quell.sync.payload import _project_id

        pid = _project_id(project_root)
        resp = httpx.delete(
            f"https://api.quelltest.com/v1/projects/{pid}",
            headers={"Authorization": f"Bearer {token}"},
            timeout=10.0,
        )
        if resp.status_code in (200, 204):
            console.print(f"[green]Project '{alias}' unlinked. All cloud data deleted.[/green]")
            # Clear local history
            history_file = project_root / ".quell" / "sync_history.json"
            if history_file.exists():
                history_file.write_text(_j.dumps([]))
        else:
            console.print(f"[red]Unlink failed: server returned {resp.status_code}[/red]")
            raise typer.Exit(1)
    except ImportError:
        console.print("[red]httpx not installed. Run: pip install httpx[/red]")
        raise typer.Exit(1)
    except Exception as exc:  # noqa: BLE001
        console.print(f"[red]Unlink failed: {exc}[/red]")
        raise typer.Exit(1)
